export const GET_LOCATIONS_REQUEST = "GET_LOCATIONS_REQUEST";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE";

export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const CART_REMOVE = "CART_REMOVE";

export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const WISHLIST_REMOVE = "WISHLIST_REMOVE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
